### ISSUE TITLE
Указываем в явном виде создаваемый объект, это облегчает код-ревью

### ISSUE THREAD

**Issue by alexeychernykh** [RuprechtKraus/MarketInterface#3]
https://github.com/RuprechtKraus/MarketInterface/blob/d9461af10e862d7a2bc7e25d46812fd7717e54fa/MarketLib/Market.cs#L42

Item itemToStock = new Item(item);

**Comment by RuprechtKraus** [comment]
Автоматически не закрылось, так как оказалось что для этого нужно писать именно "fixed #<number>"
